-- Seed finalisasi 20 Agustus 2026. Jalankan setelah schema.sql.
begin;

insert into public.admin_users(email,display_name,is_active) values ('bmnditjenpas.wp4@gmail.com','Korwil BMN',true) on conflict(email) do update set display_name=excluded.display_name,is_active=true;

insert into public.satkers(code,name,slug) values
('692307','Bapas Kelas I Pekanbaru','bapas-pekanbaru'),
('692308','Lapas Kelas IIA Pekanbaru','lapas-pekanbaru'),
('692309','Lapas Kelas IIA Bengkalis','lapas-bengkalis'),
('692310','Rutan Kelas IIB Siak Sri Indrapura','rutan-siak'),
('692311','Lapas Kelas IIA Bagansiapiapi','lapas-bagansiapiapi'),
('692312','Rutan Kelas IIB Rengat','rutan-rengat'),
('692313','Lapas Kelas IIA Tembilahan','lapas-tembilahan'),
('692314','Lapas Kelas IIB Teluk Kuantan','lapas-teluk-kuantan'),
('692315','Lapas Kelas IIB Selat Panjang','lapas-selat-panjang'),
('692316','Lapas Kelas IIA Bangkinang','lapas-bangkinang'),
('692317','Lapas Kelas IIB Pasir Pangarayan','lapas-pasir-pangarayan'),
('692484','Rutan Kelas IIB Dumai','rutan-dumai'),
('692507','Kanwil Ditjenpas Riau','kanwil-riau'),
('692519','LPKA Kelas II Pekanbaru','lpka-pekanbaru'),
('692537','Lapas Perempuan Kelas IIA Pekanbaru','lpp-pekanbaru'),
('692639','Lapas Narkotika Kelas IIB Rumbai','lapas-narkotika-rumbai'),
('692675','Rupbasan Kelas II Bengkalis','rupbasan-bengkalis'),
('692781','Rutan Kelas I Pekanbaru','rutan-pekanbaru'),
('692794','Lapas Terbuka Kelas III Rumbai','lapas-terbuka-rumbai'),
('694759','Bapas Kelas II Dumai','bapas-dumai')
on conflict(code) do update set name=excluded.name, slug=excluded.slug;

insert into public.tasks(task_key,title,description,method,source_url,source_spreadsheet_id,source_sheet,source_letter,due_date,due_label,is_active,priority,sync_config) values
('plang-rumah','Pergantian Plang Tanah dan Papan Rumah Negara','Penyampaian laporan pengamanan aset dan bukti pengisian pergantian plang tanah serta papan rumah negara.','spreadsheet','https://docs.google.com/spreadsheets/d/1_UoTVM5_CAA1-T-1sxIz67mZwTeFbxueAhNS0XFAPXU/edit?gid=0#gid=0','1_UoTVM5_CAA1-T-1sxIz67mZwTeFbxueAhNS0XFAPXU','Sheet1','Monitoring pergantian plang tanah dan papan rumah negara','2026-08-20','20 Agustus 2026',true,'tinggi','{"spreadsheetId": "1_UoTVM5_CAA1-T-1sxIz67mZwTeFbxueAhNS0XFAPXU", "sheets": ["Sheet1"]}'::jsonb),
('xray','Penghapusan X-Ray dan Body Scanner','Melengkapi identitas teknis, nomor serial, kondisi, dan dokumentasi X-Ray yang ditindaklanjuti untuk penghapusan.','spreadsheet','https://docs.google.com/spreadsheets/d/1t3IIrahsooPjPGIb2IfCNDI1gm53XtYtY19oQm3_Ryk/edit?gid=0#gid=0','1t3IIrahsooPjPGIb2IfCNDI1gm53XtYtY19oQm3_Ryk','Rekap Xray Barang','Tindak Lanjut Status X-Ray dan Body Scanner Rusak Berat',null,'Belum ditentukan',true,'tinggi','{"spreadsheetId": "1t3IIrahsooPjPGIb2IfCNDI1gm53XtYtY19oQm3_Ryk", "sheets": ["Rekap Xray Barang"]}'::jsonb),
('master-aset','Kelengkapan Master Aset','Melengkapi atribut Tanah, Rumah Negara, serta Gedung dan Bangunan pada Master Aset.','spreadsheet','https://docs.google.com/spreadsheets/d/14O64ETAtsMr_qfCdui_aP0Rr_e0gvzYL/edit?gid=1530083301#gid=1530083301','14O64ETAtsMr_qfCdui_aP0Rr_e0gvzYL','DATA RINCI','Monitoring kelengkapan Master Aset SIMAN','2026-08-20','20 Agustus 2026',true,'tinggi','{"spreadsheetId": "14O64ETAtsMr_qfCdui_aP0Rr_e0gvzYL", "sheets": ["DATA RINCI"]}'::jsonb),
('rkbmn','RKBMN SIMAN dan Non-SIMAN','Menyampaikan usulan RKBMN melalui SIMAN dan melengkapi dokumen usulan RKBMN Non-SIMAN.','spreadsheet','https://docs.google.com/spreadsheets/d/1Sp3hw2sRK8l_W7DUL3csaZpUjHxddeu25RGM3kEitu0/edit?gid=0#gid=0','1Sp3hw2sRK8l_W7DUL3csaZpUjHxddeu25RGM3kEitu0','Sheet1','Monitoring usulan RKBMN SIMAN dan Non-SIMAN Tahun 2027','2026-08-31','31 Agustus 2026',true,'tinggi','{"spreadsheetId": "1Sp3hw2sRK8l_W7DUL3csaZpUjHxddeu25RGM3kEitu0", "sheets": ["Sheet1"]}'::jsonb),
('persediaan-rusak','Tindak Lanjut Persediaan Rusak','Melengkapi dokumen tindak lanjut persediaan rusak pada sheet Rusak (sheet 2).','spreadsheet','https://docs.google.com/spreadsheets/d/1OeAZacp7wmOiKPsBiz2jFt1peHto-VHbIJ3podn9yXQ/edit?gid=0#gid=0','1OeAZacp7wmOiKPsBiz2jFt1peHto-VHbIJ3podn9yXQ','Rusak','Monitoring tindak lanjut persediaan rusak','2026-08-22','22 Agustus 2026',true,'tinggi','{"spreadsheetId": "1OeAZacp7wmOiKPsBiz2jFt1peHto-VHbIJ3podn9yXQ", "sheets": ["Rusak"]}'::jsonb)
on conflict(task_key) do update set title=excluded.title,description=excluded.description,source_url=excluded.source_url,source_spreadsheet_id=excluded.source_spreadsheet_id,source_sheet=excluded.source_sheet,source_letter=excluded.source_letter,due_date=excluded.due_date,due_label=excluded.due_label,sync_config=excluded.sync_config;

-- Requirements: plang-rumah
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'laporan','Laporan Pengamanan Aset','Data Dukung',1 from public.tasks where task_key='plang-rumah' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'capture_form','Capture Bukti Mengisi Google Form','Data Dukung',2 from public.tasks where task_key='plang-rumah' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;

-- Requirements: xray
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'merk','Merk','Identitas',1 from public.tasks where task_key='xray' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'tipe','Tipe','Identitas',2 from public.tasks where task_key='xray' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'serial_rangka','Nomor Serial Rangka','Identitas',3 from public.tasks where task_key='xray' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'serial_tabung','Nomor Serial Tabung X-Ray','Identitas',4 from public.tasks where task_key='xray' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'foto','Foto X-Ray','Dokumentasi',5 from public.tasks where task_key='xray' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;

-- Requirements: master-aset
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'kode_rt_rw','Kode RT/RW','Atribut Aset',1 from public.tasks where task_key='master-aset' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'kelurahan_desa','Kelurahan/Desa','Atribut Aset',2 from public.tasks where task_key='master-aset' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'kab_kota','Kab/Kota','Atribut Aset',3 from public.tasks where task_key='master-aset' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'provinsi','Provinsi','Atribut Aset',4 from public.tasks where task_key='master-aset' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'kode_pos','Kode Pos','Atribut Aset',5 from public.tasks where task_key='master-aset' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'latitude','Latitude','Atribut Aset',6 from public.tasks where task_key='master-aset' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'longitude','Longitude','Atribut Aset',7 from public.tasks where task_key='master-aset' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'foto','Foto','Atribut Aset',8 from public.tasks where task_key='master-aset' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;

-- Requirements: rkbmn
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'surat_non_siman','Surat Usulan RKBMN Non-SIMAN','Non-SIMAN',1 from public.tasks where task_key='rkbmn' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'matriks_pengadaan','Matriks Usulan Pengadaan','Non-SIMAN',2 from public.tasks where task_key='rkbmn' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'surat_pernyataan','Surat Pernyataan','Non-SIMAN',3 from public.tasks where task_key='rkbmn' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'profil_satker','Profil Satker','Non-SIMAN',4 from public.tasks where task_key='rkbmn' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'usulan_siman','Usulan RKBMN SIMAN','SIMAN',5 from public.tasks where task_key='rkbmn' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;

-- Requirements: persediaan-rusak
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'dokumen_1','Surat Permohonan dan Daftar BMN','Data Dukung',1 from public.tasks where task_key='persediaan-rusak' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'dokumen_2','SK Tim Penjualan BMN','Data Dukung',2 from public.tasks where task_key='persediaan-rusak' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'dokumen_3','SPTJM','Data Dukung',3 from public.tasks where task_key='persediaan-rusak' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'dokumen_4','Berita Acara Penelitian','Data Dukung',4 from public.tasks where task_key='persediaan-rusak' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'dokumen_5','Surat Pernyataan Tidak Mengganggu Tusi','Data Dukung',5 from public.tasks where task_key='persediaan-rusak' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'dokumen_6','Surat Pernyataan Nilai Limit','Data Dukung',6 from public.tasks where task_key='persediaan-rusak' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'dokumen_7','Telaahan Staf','Data Dukung',7 from public.tasks where task_key='persediaan-rusak' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'dokumen_8','Cetakan Laporan Persediaan','Data Dukung',8 from public.tasks where task_key='persediaan-rusak' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'dokumen_9','Cetakan Persediaan Rusak','Data Dukung',9 from public.tasks where task_key='persediaan-rusak' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;
insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select id,'dokumen_10','Dokumentasi Foto Persediaan Rusak','Data Dukung',10 from public.tasks where task_key='persediaan-rusak' on conflict(task_id,requirement_key) do update set label=excluded.label,track=excluded.track,display_order=excluded.display_order;

-- Assignments: plang-rumah
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692307' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692308' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692309' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692310' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692311' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692312' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692313' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Laporan Pengamanan Aset", "Capture Bukti Mengisi Google Form"]'::jsonb,'{"required": 2, "completed": 0, "note": "belum melaporkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692314' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692315' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Laporan Pengamanan Aset", "Capture Bukti Mengisi Google Form"]'::jsonb,'{"required": 2, "completed": 0, "note": "belum melaporkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692316' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692317' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692484' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692507' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692519' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692537' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692639' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692781' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Laporan Pengamanan Aset", "Capture Bukti Mengisi Google Form"]'::jsonb,'{"required": 2, "completed": 0, "note": "belum melaporkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='692794' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 2, "completed": 2, "note": ""}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='plang-rumah' and s.code='694759' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;

-- Assignments: xray
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,80,'proses','["Rekap Xray Barang: Nomor Serial Tabung X-Ray"]'::jsonb,'{"required": 5, "completed": 4, "sheets": ["Rekap Xray Barang"]}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='xray' and s.code='692311' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 5, "completed": 5, "sheets": ["Rekap Xray Barang"]}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='xray' and s.code='692316' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 5, "completed": 5, "sheets": ["Rekap Xray Barang"]}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='xray' and s.code='692309' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 5, "completed": 5, "sheets": ["Rekap Xray Barang"]}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='xray' and s.code='692308' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,80,'proses','["Rekap Xray Barang: Foto X-Ray"]'::jsonb,'{"required": 5, "completed": 4, "sheets": ["Rekap Xray Barang"]}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='xray' and s.code='692313' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 5, "completed": 5, "sheets": ["Rekap Xray Barang"]}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='xray' and s.code='692317' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Rekap Xray Barang: Merk", "Rekap Xray Barang: Tipe", "Rekap Xray Barang: Nomor Serial Rangka", "Rekap Xray Barang: Nomor Serial Tabung X-Ray", "Rekap Xray Barang: Foto X-Ray"]'::jsonb,'{"required": 5, "completed": 0, "sheets": ["Rekap Xray Barang"]}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='xray' and s.code='692639' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 5, "completed": 5, "sheets": ["Rekap Xray Barang"]}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='xray' and s.code='692781' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,80,'proses','["Rekap Xray Barang: Nomor Serial Tabung X-Ray"]'::jsonb,'{"required": 5, "completed": 4, "sheets": ["Rekap Xray Barang"]}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='xray' and s.code='692310' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;

-- Assignments: master-aset
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,75,'proses','["4 aset belum lengkap: Kode Pos", "10 aset belum lengkap: Latitude", "10 aset belum lengkap: Longitude"]'::jsonb,'{"required": 96, "completed": 72, "nup": 12}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692307' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,50,'proses','["6 aset belum lengkap: Kode RT/RW", "6 aset belum lengkap: Kode Pos", "6 aset belum lengkap: Latitude", "6 aset belum lengkap: Longitude"]'::jsonb,'{"required": 48, "completed": 24, "nup": 6}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='694759' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 56, "completed": 56, "nup": 7}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692507' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,70,'proses','["8 aset belum lengkap: Kode RT/RW", "25 aset belum lengkap: Kode Pos", "15 aset belum lengkap: Latitude", "15 aset belum lengkap: Longitude", "7 aset belum lengkap: Kelurahan/Desa"]'::jsonb,'{"required": 232, "completed": 162, "nup": 29}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692311' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,90,'proses','["10 aset belum lengkap: Kode Pos"]'::jsonb,'{"required": 104, "completed": 94, "nup": 13}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692316' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,100,'selesai','[]'::jsonb,'{"required": 144, "completed": 144, "nup": 18}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692309' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,65,'proses','["42 aset belum lengkap: Kode Pos", "44 aset belum lengkap: Latitude", "44 aset belum lengkap: Longitude"]'::jsonb,'{"required": 376, "completed": 246, "nup": 47}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692308' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,76,'proses','["12 aset belum lengkap: Kode Pos", "17 aset belum lengkap: Kode RT/RW", "4 aset belum lengkap: Latitude", "4 aset belum lengkap: Longitude"]'::jsonb,'{"required": 152, "completed": 115, "nup": 19}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692313' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,86,'proses','["10 aset belum lengkap: Kode Pos", "2 aset belum lengkap: Kode RT/RW", "6 aset belum lengkap: Latitude", "6 aset belum lengkap: Longitude"]'::jsonb,'{"required": 176, "completed": 152, "nup": 22}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692317' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,90,'proses','["11 aset belum lengkap: Kode RT/RW"]'::jsonb,'{"required": 112, "completed": 101, "nup": 14}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692315' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,64,'proses','["13 aset belum lengkap: Kode Pos", "12 aset belum lengkap: Latitude", "12 aset belum lengkap: Longitude", "6 aset belum lengkap: Kode RT/RW", "4 aset belum lengkap: Kelurahan/Desa", "4 aset belum lengkap: Kab/Kota", "4 aset belum lengkap: Provinsi"]'::jsonb,'{"required": 152, "completed": 97, "nup": 19}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692314' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,90,'proses','["18 aset belum lengkap: Kode RT/RW", "5 aset belum lengkap: Kode Pos", "1 aset belum lengkap: Kelurahan/Desa"]'::jsonb,'{"required": 240, "completed": 216, "nup": 30}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692639' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,93,'proses','["3 aset belum lengkap: Kode RT/RW", "1 aset belum lengkap: Latitude", "1 aset belum lengkap: Longitude", "1 aset belum lengkap: Kelurahan/Desa", "2 aset belum lengkap: Kode Pos"]'::jsonb,'{"required": 112, "completed": 104, "nup": 14}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692537' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,85,'proses','["7 aset belum lengkap: Kode RT/RW", "1 aset belum lengkap: Kelurahan/Desa", "2 aset belum lengkap: Kode Pos", "2 aset belum lengkap: Latitude", "2 aset belum lengkap: Longitude"]'::jsonb,'{"required": 96, "completed": 82, "nup": 12}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692794' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,72,'proses','["10 aset belum lengkap: Kode RT/RW", "6 aset belum lengkap: Latitude", "6 aset belum lengkap: Longitude", "5 aset belum lengkap: Kode Pos"]'::jsonb,'{"required": 96, "completed": 69, "nup": 12}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692519' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,80,'proses','["19 aset belum lengkap: Kode Pos", "14 aset belum lengkap: Kode RT/RW", "4 aset belum lengkap: Latitude", "4 aset belum lengkap: Longitude", "2 aset belum lengkap: Kelurahan/Desa", "2 aset belum lengkap: Kab/Kota", "2 aset belum lengkap: Provinsi"]'::jsonb,'{"required": 232, "completed": 185, "nup": 29}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692781' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,76,'proses','["30 aset belum lengkap: Kode Pos", "15 aset belum lengkap: Latitude", "15 aset belum lengkap: Longitude", "2 aset belum lengkap: Kode RT/RW", "2 aset belum lengkap: Kelurahan/Desa"]'::jsonb,'{"required": 264, "completed": 200, "nup": 33}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692484' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,99,'proses','["1 aset belum lengkap: Kelurahan/Desa"]'::jsonb,'{"required": 144, "completed": 143, "nup": 18}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692312' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,99,'proses','["2 aset belum lengkap: Kode RT/RW"]'::jsonb,'{"required": 200, "completed": 198, "nup": 25}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='master-aset' and s.code='692310' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;

-- Assignments: rkbmn
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692307' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692308' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,20,'proses','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker"]'::jsonb,'{"required": 5, "completed": 1, "siman": "Sudah Mengusulkan''"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692309' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,20,'proses','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker"]'::jsonb,'{"required": 5, "completed": 1, "siman": "Sudah Mengusulkan''"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692310' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692311' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692312' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,20,'proses','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker"]'::jsonb,'{"required": 5, "completed": 1, "siman": "Sudah Mengusulkan''"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692313' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692314' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692315' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692316' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692317' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,20,'proses','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker"]'::jsonb,'{"required": 5, "completed": 1, "siman": "Sudah Mengusulkan''"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692484' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692507' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692519' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,20,'proses','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker"]'::jsonb,'{"required": 5, "completed": 1, "siman": "Sudah Mengusulkan''"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692537' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692639' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692781' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker", "Usulan RKBMN SIMAN"]'::jsonb,'{"required": 5, "completed": 0, "siman": "Belum Mengusulkan"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='692794' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,20,'proses','["Surat Usulan RKBMN Non SIMAN", "Matriks Usulan Pengadaan", "Surat Pernyataan", "Profil Satker"]'::jsonb,'{"required": 5, "completed": 1, "siman": "Sudah Mengusulkan''"}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='rkbmn' and s.code='694759' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;

-- Assignments: persediaan-rusak
insert into public.task_assignments(task_id,satker_id,progress,status,missing,source_snapshot,last_synced_at) select t.id,s.id,0,'belum','["Surat Permohonan dan Daftar Barang Milik Negara yang Diusulkan Penjualan", "SK Tim Penjualan BMN", "SPTJM", "Berita Acara Penelitian", "Surat Pernyataan Tidak Mengganggu Tusi", "Surat Pernyataan Nilai Limit", "Telaahan Staf", "Cetakan Laporan Persediaan", "Cetakan Persediaa Rusak", "Dokumentasi Foto Persediaan Rusak"]'::jsonb,'{"required": 10, "completed": 0, "total_value": 27275680.0}'::jsonb,now() from public.tasks t cross join public.satkers s where t.task_key='persediaan-rusak' and s.code='692311' on conflict(task_id,satker_id) do update set progress=excluded.progress,status=excluded.status,missing=excluded.missing,source_snapshot=excluded.source_snapshot,last_synced_at=excluded.last_synced_at;

-- Pekerjaan: Pemusnahan Persediaan Usang
insert into public.tasks(task_key,title,description,method,source_url,source_spreadsheet_id,source_sheet,source_letter,due_label,is_active,priority) values ('persediaan-usang','Tindak Lanjut Pemusnahan Persediaan Usang','Seluruh satker yang memiliki persediaan usang telah mengajukan usulan dan saat ini menunggu persetujuan dari Pengguna Barang.','spreadsheet','https://docs.google.com/spreadsheets/d/1OeAZacp7wmOiKPsBiz2jFt1peHto-VHbIJ3podn9yXQ/edit?gid=0#gid=0','1OeAZacp7wmOiKPsBiz2jFt1peHto-VHbIJ3podn9yXQ','Usang','Monitoring tindak lanjut pemusnahan persediaan usang','Tidak ada tenggat',true,'normal') on conflict(task_key) do update set title=excluded.title,description=excluded.description,is_active=true;
with r(k,l,o) as (values ('surat_permohonan','Surat Permohonan Satker',1),('sk_tim_pemusnahan','SK Tim Pemusnahan',2),('sptjm','SPTJM',3),('tidak_ganggu_tusi','Surat Pernyataan Tidak Mengganggu Tusi',4),('berita_acara','Berita Acara Penelitian Persediaan',5),('daftar_persediaan','Cetakan Daftar Persediaan Usang/Rusak',6),('dokumentasi','Dokumentasi BMN Terkini',7),('telaah_staf','Telaah Staf',8)) insert into public.task_requirements(task_id,requirement_key,label,track,display_order) select t.id,r.k,r.l,'Data Dukung',r.o from r cross join public.tasks t where t.task_key='persediaan-usang' on conflict(task_id,requirement_key) do update set label=excluded.label,display_order=excluded.display_order;
with a(code) as (values ('692308'),('692309'),('692311'),('692312'),('692314'),('692315'),('692316'),('692317'),('692484'),('692519'),('692537'),('692781'),('692794')) insert into public.task_assignments(task_id,satker_id,progress,status,missing,last_synced_at) select t.id,s.id,100,'persetujuan','[]'::jsonb,now() from a join public.satkers s on s.code=a.code cross join public.tasks t where t.task_key='persediaan-usang' on conflict(task_id,satker_id) do update set progress=100,status='persetujuan',missing='[]'::jsonb,last_synced_at=now();

commit;
