import { useEffect, useMemo, useState } from 'react'
import { Check, Clipboard, Database, Eye, Search, ShieldCheck } from 'lucide-react'
import { satkers } from './data'
import { calculateAkunMitraProgress, createEmptyAkunMitraRecord, type AkunMitraPhotoSlot, type AkunMitraRecord } from './akunMitra'
import type { MitraDataRepository } from './lib/mitraDataRepository'
import { activeMitraRepository } from './lib/activeMitraRepository'

const storageName=import.meta.env.DEV?'SQLite lokal localhost':'Supabase'
const storageNotice=import.meta.env.DEV?'Teks dan foto berasal dari database lokal komputer ini. Tidak terhubung ke Supabase produksi.':'Teks dan foto berasal dari database Supabase terpusat.'
const value=(v:string)=>v||'Belum diisi'
export function AkunMitraAdmin({repository=activeMitraRepository}:{repository?:MitraDataRepository}){
 const [selected,setSelected]=useState(''),[query,setQuery]=useState(''),[copied,setCopied]=useState(''),[savedRecords,setSavedRecords]=useState<AkunMitraRecord[]>([]),[loadError,setLoadError]=useState('')
 useEffect(()=>{let active=true;repository.loadAll().then(records=>{if(active)setSavedRecords(records)}).catch(error=>{if(active)setLoadError(error instanceof Error?error.message:'SQLite lokal belum dapat dibaca.')});return()=>{active=false}},[repository])
 const records=useMemo(()=>{const byCode=new Map(savedRecords.map(record=>[record.satkerCode,record]));return satkers.filter(s=>s.code!=='692507').map(s=>byCode.get(s.code)??createEmptyAkunMitraRecord(s.code))},[savedRecords])
 const rows=records.map(record=>({record,satker:satkers.find(s=>s.code===record.satkerCode)!,progress:calculateAkunMitraProgress(record)})).filter(x=>`${x.satker.name} ${x.satker.code}`.toLowerCase().includes(query.toLowerCase()))
 const current=records.find(r=>r.satkerCode===selected)
 const copy=async(label:string,text:string)=>{await navigator.clipboard?.writeText(text);setCopied(label);setTimeout(()=>setCopied(''),1200)}
 const replaceRecord=(saved:AkunMitraRecord)=>setSavedRecords(current=>[...current.filter(record=>record.satkerCode!==saved.satkerCode),saved])
 return <section className="admin-page akun-admin-page">
  <div className="panel-head"><div><h2>Data Akun Mitra</h2><p>Rekap prototipe lokal untuk menyalin data satker ke web Mitra secara manual.</p></div><span className="visibility open">Lokal · Korwil</span></div>
  <div className="privacy-warning"><ShieldCheck/><div><strong>{storageName}</strong><p>{storageNotice}</p></div></div>
  {loadError&&<div className="auth-message error">{loadError}</div>}
  <div className="akun-admin-layout"><aside className="akun-admin-list"><label className="akun-admin-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari satker"/></label>{rows.map(x=><button key={x.satker.code} className={selected===x.satker.code?'active':''} onClick={()=>setSelected(x.satker.code)}><div><strong>{x.satker.name}</strong><span>{x.satker.code} · {x.record.status.replace('_',' ')}</span></div><b>{x.progress.total}%</b></button>)}</aside>
   <div className="akun-admin-detail">{current?<RecordDetail record={current} copied={copied} copy={copy} repository={repository} onChanged={replaceRecord}/>:<div className="document-empty"><Database/><strong>Pilih satuan kerja</strong><p>Data Unit, Pejabat KPB, dan Operator akan tampil di sini.</p></div>}</div>
  </div>
 </section>
}

function RecordDetail({record,copied,copy,repository,onChanged}:{record:AkunMitraRecord;copied:string;copy:(label:string,text:string)=>void;repository:MitraDataRepository;onChanged:(record:AkunMitraRecord)=>void}){
 const [reviewNote,setReviewNote]=useState(record.reviewNote),[actionError,setActionError]=useState(''),[reviewing,setReviewing]=useState(false),[editing,setEditing]=useState(false),[editable,setEditable]=useState(record)
 const satker=satkers.find(s=>s.code===record.satkerCode)!
 const openPhoto=async(slot:AkunMitraPhotoSlot)=>{const file=await repository.getPhoto(record.satkerCode,slot);if(!file)return;const url=URL.createObjectURL(file);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),30000)}
 const photos:Array<{slot:AkunMitraPhotoSlot;label:string;name:string}>=[{slot:'unit',label:'Foto Gedung',name:record.unit.fotoGedungFile},{slot:'kpb',label:'Pasfoto Pejabat KPB',name:record.kpb.pasFotoFile},{slot:'operator',label:'Pasfoto Operator',name:record.operator.pasFotoFile}]
 const review=async(decision:'perbaikan'|'selesai')=>{if(decision==='perbaikan'&&!reviewNote.trim()){setActionError('Catatan perbaikan wajib diisi.');return}setReviewing(true);setActionError('');try{onChanged(await repository.review(record.satkerCode,decision,reviewNote))}catch(error){setActionError(error instanceof Error?error.message:'Review belum dapat disimpan.')}finally{setReviewing(false)}}
 const updateAccepted=async()=>{setReviewing(true);setActionError('');try{const saved=await repository.updateAccepted({...editable,status:'selesai'});onChanged(saved);setEditable(saved);setEditing(false)}catch(error){setActionError(error instanceof Error?error.message:'Koreksi Korwil belum dapat disimpan.')}finally{setReviewing(false)}}
 const sections=[
  {title:'Data Unit',items:[['Nama Unit',satker.name],['Kode Satker 20 Digit',`137040900${record.satkerCode}000KD`],['NPWP Kantor',record.unit.npwpKantor],['Email Kantor',record.unit.emailKantor],['Telepon',record.unit.telepon],['Alamat',record.unit.alamat],['RT/RW',record.unit.rtRw],['Kode Pos',record.unit.kodepos],['File Foto Gedung',record.unit.fotoGedungFile]]},
  {title:'Data Pejabat KPB',items:[['Nama Pejabat KPB',record.kpb.nama],['Jabatan KPB',record.kpb.jabatan],['Email KPB',record.kpb.email],['NIP KPB',record.kpb.nip],['NIK KPB',record.kpb.nik],['Nomor HP KPB',record.kpb.noHp],['Tempat Lahir KPB',record.kpb.tempatLahir],['Tanggal Lahir KPB',record.kpb.tanggalLahir],['Jenis Kelamin KPB',record.kpb.jenisKelamin],['Alamat KPB',record.kpb.alamat],['RT/RW KPB',record.kpb.rtRw],['Kode Pos KPB',record.kpb.kodepos],['File Pasfoto KPB',record.kpb.pasFotoFile]]},
  {title:'Data Operator',items:[['Nama Operator',record.operator.nama],['Jabatan Operator',record.operator.jabatan],['Email Operator',record.operator.email],['NIP Operator',record.operator.nip],['NIK Operator',record.operator.nik],['Nomor HP Operator',record.operator.noHp],['Tempat Lahir Operator',record.operator.tempatLahir],['Tanggal Lahir Operator',record.operator.tanggalLahir],['Jenis Kelamin Operator',record.operator.jenisKelamin],['Alamat Operator',record.operator.alamat],['RT/RW Operator',record.operator.rtRw],['Kode Pos Operator',record.operator.kodepos],['File Pasfoto Operator',record.operator.pasFotoFile]]},
 ]
 return <div><div className="akun-record-title"><div><span>{satker.code}</span><h3>{satker.name}</h3></div><Eye/></div>{record.status==='siap_verifikasi'&&<div className="akun-review-panel"><label>Catatan review<textarea aria-label="Catatan review" value={reviewNote} onChange={event=>setReviewNote(event.target.value)} placeholder="Wajib untuk meminta perbaikan"/></label>{actionError&&<div className="auth-message error">{actionError}</div>}<div className="akun-actions"><button className="ghost" disabled={reviewing} onClick={()=>void review('perbaikan')}>Perlu Perbaikan</button><button className="primary" disabled={reviewing} onClick={()=>void review('selesai')}>Terima</button></div></div>}{record.status==='selesai'&&<div className="akun-review-panel"><strong>Status diterima · satker tetap terkunci</strong>{editing?<AcceptedEditor record={editable} onChange={setEditable}/>:<button className="ghost" onClick={()=>setEditing(true)}>Edit data Korwil</button>}{editing&&<div className="akun-actions"><button className="ghost" onClick={()=>{setEditable(record);setEditing(false)}}>Batal</button><button className="primary" disabled={reviewing} onClick={()=>void updateAccepted()}>Simpan koreksi Korwil</button></div>}<label>Catatan perbaikan setelah diterima<textarea aria-label="Catatan perbaikan setelah diterima" value={reviewNote} onChange={event=>setReviewNote(event.target.value)}/></label><button className="ghost" disabled={reviewing} onClick={()=>void review('perbaikan')}>Buka untuk Perbaikan Satker</button>{actionError&&<div className="auth-message error">{actionError}</div>}</div>}{record.reviewNote&&<div className="akun-review-note"><strong>Catatan review</strong><p>{record.reviewNote}</p></div>}<div className="akun-admin-photos">{photos.map(photo=><button key={photo.slot} disabled={!photo.name} onClick={()=>void openPhoto(photo.slot)}><Eye/><span><strong>{photo.label}</strong><small>{photo.name||'Belum diunggah'}</small></span></button>)}</div>{sections.map(section=><section className="akun-record-section" key={section.title}><h4>{section.title}</h4><div className="akun-copy-grid">{section.items.map(([label,text])=><div key={label}><span>{label}</span><strong className={text?'':'empty'}>{value(text)}</strong><button aria-label={`Salin ${label}`} disabled={!text} onClick={()=>copy(label,text)}>{copied===label?<Check/>:<Clipboard/>}{copied===label?'Tersalin':'Salin'}</button></div>)}</div></section>)}</div>
}

const adminLabels:Record<string,string>={npwpKantor:'NPWP kantor',emailKantor:'Email kantor',telepon:'Telepon',alamat:'Alamat',rtRw:'RT/RW',kodepos:'Kode pos',fotoGedungFile:'Nama file foto gedung',nama:'Nama',jabatan:'Jabatan',email:'Email',nip:'NIP',nik:'NIK',noHp:'Nomor HP',tempatLahir:'Tempat lahir',tanggalLahir:'Tanggal lahir',jenisKelamin:'Jenis kelamin',pasFotoFile:'Nama file pasfoto'}
function AcceptedEditor({record,onChange}:{record:AkunMitraRecord;onChange:(record:AkunMitraRecord)=>void}){
 const groups=['unit','kpb','operator'] as const
 return <div className="akun-admin-edit">{groups.map(group=><fieldset key={group}><legend>{group==='unit'?'Data Unit':group==='kpb'?'Pejabat KPB':'Operator'}</legend>{Object.entries(record[group]).map(([key,text])=><label key={key}>{adminLabels[key]??key}<input aria-label={`${adminLabels[key]??key} (Korwil)`} value={text} onChange={event=>onChange({...record,[group]:{...record[group],[key]:event.target.value}})}/></label>)}</fieldset>)}</div>
}
