import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from "jsr:@supabase/supabase-js@2"
import { importPKCS8, SignJWT } from "npm:jose@5.9.6"

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}})
const safe=(name:string)=>name.replace(/[\\/:*?"<>|]+/g,'-').replace(/\s+/g,' ').trim().slice(0,110)
async function readCredentials(db:any){const envEmail=Deno.env.get('GOOGLE_SERVICE_ACCOUNT_EMAIL'),envKey=Deno.env.get('GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY');if(envEmail&&envKey)return {type:'service_account',client_email:envEmail,private_key:envKey} as any;const{data:stored}=await db.from('integration_secrets').select('secret_key,secret_value').in('secret_key',['google_service_account_json','google_drive_root_folder_id']);const map=Object.fromEntries((stored??[]).map(x=>[x.secret_key,x.secret_value]));if(map.google_service_account_json){const parsed=typeof map.google_service_account_json==='string'?JSON.parse(map.google_service_account_json):map.google_service_account_json;return parsed}return null}

async function googleToken(credentials:any){
 if(credentials.type==='authorized_user'){
  const response=await fetch(credentials.token_uri??'https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:credentials.client_id,client_secret:credentials.client_secret,refresh_token:credentials.refresh_token,grant_type:'refresh_token'})});if(!response.ok)throw new Error('Refresh token Google Drive tidak valid.');return(await response.json()).access_token as string
 }
 const key=await importPKCS8(String(credentials.private_key).replace(/\\n/g,'\n'),'RS256');const assertion=await new SignJWT({scope:'https://www.googleapis.com/auth/drive'}).setProtectedHeader({alg:'RS256',typ:'JWT'}).setIssuer(credentials.client_email).setSubject(credentials.client_email).setAudience('https://oauth2.googleapis.com/token').setIssuedAt().setExpirationTime('1h').sign(key);const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});if(!response.ok)throw new Error('Autentikasi Google Drive gagal.');return(await response.json()).access_token as string
}
async function findOrCreateFolder(token:string,name:string,parent:string){const q=`'${parent}' in parents and name='${name.replaceAll("'","\\'")}' and mimeType='application/vnd.google-apps.folder' and trashed=false`;const list=await fetch(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=files(id,name)&supportsAllDrives=true`,{headers:{Authorization:`Bearer ${token}`}});if(!list.ok)throw new Error('Tidak dapat membaca folder Google Drive.');const found=(await list.json()).files?.[0];if(found)return found.id as string;const create=await fetch('https://www.googleapis.com/drive/v3/files?fields=id&supportsAllDrives=true',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',parents:[parent]})});if(!create.ok)throw new Error(`Tidak dapat membuat folder ${name}.`);return(await create.json()).id as string}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405)
try{const auth=req.headers.get('Authorization');if(!auth)return json({error:'Unauthorized'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const userDb=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const{data:profile}=await userDb.rpc('get_my_admin_profile');if(!profile)return json({error:'Akses Korwil diperlukan.'},403)
const db=createClient(url,service,{auth:{persistSession:false}})
let credentials:any=await readCredentials(db)
let root:string|null=Deno.env.get('GOOGLE_DRIVE_ROOT_FOLDER_ID')??null
if(!credentials||!root){const{data:stored}=await db.from('integration_secrets').select('secret_key,secret_value').in('secret_key',['google_service_account_json','google_drive_root_folder_id']);const map=Object.fromEntries((stored??[]).map(x=>[x.secret_key,x.secret_value]));if(!credentials&&map.google_service_account_json)credentials=typeof map.google_service_account_json==='string'?JSON.parse(map.google_service_account_json):map.google_service_account_json;if(!root)root=map.google_drive_root_folder_id??null}
if(!credentials||!root)return json({error:'Konektor Google Drive belum dikonfigurasi. Hubungi admin untuk menyiapkan Service Account.'},503)
const body=await req.json(),submissionId=String(body.submissionId??'');const{data:submission,error}=await db.from('submissions').select('id,submission_number,status,submitted_at,tasks(title),satkers(code,name),supporting_documents(id,original_filename,stored_path,mime_type,archive_status)').eq('id',submissionId).single();if(error||!submission)return json({error:'Pengajuan tidak ditemukan.'},404);if(submission.status!=='diterima')return json({error:'Hanya pengajuan yang diterima yang dapat diarsipkan.'},409)
const token=await googleToken(credentials);const year=String(new Date(submission.submitted_at??Date.now()).getFullYear());const yearFolder=await findOrCreateFolder(token,year,root);const taskFolder=await findOrCreateFolder(token,safe((submission.tasks as any).title),yearFolder);const satker= submission.satkers as any;const satkerFolder=await findOrCreateFolder(token,safe(`${satker.code} - ${satker.name}`),taskFolder);const receiptFolder=await findOrCreateFolder(token,submission.submission_number,satkerFolder);const archived=[]
for(const document of submission.supporting_documents as any[]){if(document.archive_status==='drive')continue;if(!document.stored_path){await db.from('supporting_documents').update({archive_status:'drive',review_note:(document.review_note??'')+' [tautan sheet - tidak ada file untuk diarsipkan]'}).eq('id',document.id);continue}const{data:file,error:downloadError}=await db.storage.from('submission-inbox').download(document.stored_path);if(downloadError)throw downloadError;const metadata={name:safe(document.original_filename),parents:[receiptFolder]};const form=new FormData();form.append('metadata',new Blob([JSON.stringify(metadata)],{type:'application/json'}));form.append('file',file,metadata.name);const upload=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink&supportsAllDrives=true',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});if(!upload.ok)throw new Error(`Gagal mengarsipkan ${metadata.name}.`);const drive=await upload.json();await db.from('supporting_documents').update({drive_file_id:drive.id,drive_url:drive.webViewLink,archive_status:'drive'}).eq('id',document.id);await db.storage.from('submission-inbox').remove([document.stored_path]);archived.push({id:document.id,driveFileId:drive.id,driveUrl:drive.webViewLink})}
return json({status:'success',submissionNumber:submission.submission_number,archivedCount:archived.length,files:archived})}catch(error){console.error(error);return json({error:error instanceof Error?error.message:'Terjadi kesalahan arsip.'},500)}})
